module.exports={
    soma(a,b){
        console.log(a+b)
    },
    sub(a,b){
        console.log(a-b)
    },
    multiplicacao(a,b){
        console.log(a*b)
    },
    divisao(a,b){
        console.log(a/b)
    }
}